import { TenderAwarded } from "./tender-awarded";
import { TenderBidder } from "./tender-bidder";
import { TenderClassification } from "./tender-classification";
import { TenderDates } from "./tender-dates";
import { TenderFieldChange } from "./tender-field-change";
import { TenderLocalContentRequirement } from "./tender-local-content-requirment";
import { TenderLocalDoc } from "./tender-local-doc";
import { TenderStatusHistory } from "./tender-status-history";

export interface Tender {
  id: string;
  stender_id?: string;
  details_url?: string;
  reference_number?: string;
  tender_number?: string;
  name: string;
  agency_name?: string;
  tender_type?: string;
  purpose?: string;
  documents_price_sar?: string;
  competition_status?: string;
  remaining_time_text?: string;
  contract_duration?: string | null;
  insurance_required?: string | null;
  submission_method?: string;
  preliminary_guarantee?: string;
  preliminary_guarantee_address?: string;
  final_guarantee_percent?: string;
  award_number?: string | null;
  agreement_type?: string | null;
  agreement_duration?: string | null;
  beneficiary_entities?: string | null;
  publish_date?: string;
  awarding_published?: boolean;
  awarding_last_checked_at?: string;
  local_content_exists?: boolean;
  last_change_summary?: string | null;
  created_at: string;
  updated_at: string;
  dates?: TenderDates;
  classification?: TenderClassification;
  local_content_requirement?: TenderLocalContentRequirement;
  bidders?: TenderBidder[];
  awarded?: TenderAwarded[];
  local_docs?: TenderLocalDoc[];
  status_history?: TenderStatusHistory[];
  field_changes?: TenderFieldChange[];
  [key: string]: unknown;
}